import { useState, useEffect, useCallback, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Sparkles,
  Copy,
  Mail,
  Linkedin,
  Loader2,
  AlertCircle,
  X,
  CheckCircle,
  RefreshCw,
  MessageSquare,
  Plus,
} from 'lucide-react';
import { campaignsApi } from '../api/campaigns';
import { leadsApi } from '../api/leads';
import { messagesApi } from '../api/messages';
import { useToast } from '../hooks/useToast';

const fadeUp = {
  initial: { opacity: 0, y: 16 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.3 },
};

const STATUS_STYLE = {
  draft: { label: 'Brouillon', cls: 'bg-gray-100 text-gray-600' },
  queued: { label: 'En attente', cls: 'bg-amber-100 text-amber-700' },
  sent: { label: 'Envoyé', cls: 'bg-blue-100 text-blue-700' },
  delivered: { label: 'Livré', cls: 'bg-green-100 text-green-700' },
  opened: { label: 'Ouvert', cls: 'bg-green-100 text-green-700' },
  failed: { label: 'Échec', cls: 'bg-red-100 text-red-600' },
  cancelled: { label: 'Annulé', cls: 'bg-gray-100 text-gray-500' },
};

const SENTIMENT_STYLE = {
  positive: { label: 'Intérêt détecté', cls: 'bg-green-100 text-green-700' },
  negative: { label: 'Rejet', cls: 'bg-red-100 text-red-600' },
  neutral: { label: 'Neutre', cls: 'bg-gray-100 text-gray-600' },
  unknown: { label: '', cls: '' },
};

const KAWANAH_SITE_URL = 'https://tourisme.kawanah.com/';
const KAWANAH_LOGO_PATH = '/tourisme-logo.png';

const escapeHtml = (value) =>
  String(value || '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');

const linkifyHtml = (value) =>
  escapeHtml(value).replace(
    /(https?:\/\/[^\s<]+|(?<!\w)([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}(?:\/[^\s<]*)?)/g,
    (url) => {
      const href = url.startsWith('http') ? url : `https://${url}`;
      return `<a href="${href}" style="color:#149a9d;text-decoration:none;">${url}</a>`;
    }
  );

const bodyToHtml = (body, logoSrc = KAWANAH_LOGO_PATH) => {
  const paragraphs = String(body || '')
    .split(/\n{2,}/)
    .map((part) => part.trim())
    .filter(Boolean)
    .map((part) => `<p style="margin:0 0 14px;">${linkifyHtml(part).replaceAll('\n', '<br>')}</p>`)
    .join('');

  return `<div style="font-family:Arial,Helvetica,sans-serif;color:#1f2937;line-height:1.55;font-size:15px;max-width:620px;">
${paragraphs}
<div style="margin-top:24px;padding-top:16px;border-top:1px solid #e5e7eb;">
  <img src="${logoSrc}" alt="Kawanah Tourisme" width="220" style="display:block;width:220px;max-width:100%;height:auto;margin:0 0 8px;" />
  <a href="${KAWANAH_SITE_URL}" style="color:#149a9d;text-decoration:none;font-size:13px;">${KAWANAH_SITE_URL}</a>
</div>
</div>`;
};

const getLogoDataUrl = async () => {
  const response = await fetch(KAWANAH_LOGO_PATH);
  const blob = await response.blob();
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
};

const copyRichEmail = async (body) => {
  const logoDataUrl = await getLogoDataUrl();
  const html = bodyToHtml(body, logoDataUrl);
  const plain = `${body}\n\n${KAWANAH_SITE_URL}`;

  if (window.ClipboardItem && navigator.clipboard.write) {
    await navigator.clipboard.write([
      new ClipboardItem({
        'text/html': new Blob([html], { type: 'text/html' }),
        'text/plain': new Blob([plain], { type: 'text/plain' }),
      }),
    ]);
    return;
  }

  await navigator.clipboard.writeText(plain);
};

// ─── Modal génération IA ──────────────────────────────────────────────────────
function GenerateModal({
  onClose,
  onSaved,
  initialLeadId = '',
  initialLeadName = '',
  existingMessage = null,
}) {
  const [leads, setLeads] = useState([]);
  const [selectedLead, setSelectedLead] = useState(initialLeadId ? String(initialLeadId) : '');
  const [channel, setChannel] = useState(existingMessage?.channel || 'email');
  const [tone, setTone] = useState('friendly');
  const [generated, setGenerated] = useState(null);
  const [editedSubject, setEditedSubject] = useState(existingMessage?.subject || '');
  const [editedBody, setEditedBody] = useState(existingMessage?.body || '');
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);
  const [customInstructions, setCustomInstructions] = useState('');
  const autoGeneratedRef = useRef(false);
  const isTargeted = Boolean(initialLeadId);

  useEffect(() => {
    leadsApi
      .list({ per_page: 100, page: 1 })
      .then((r) => setLeads(r.data.leads || []))
      .catch(() => {});
  }, []);

  const handleGenerate = useCallback(
    async (instructionsOverride = customInstructions) => {
      const leadId = selectedLead || (initialLeadId ? String(initialLeadId) : '');
      if (!leadId) return;
      const instructions = String(instructionsOverride || '').trim();
      setLoading(true);
      setError(null);
      setGenerated(null);
      try {
        const res = await messagesApi.generate(leadId, {
          channel,
          tone,
          sender_name: 'Laetitia',
          custom_instructions: instructions || undefined,
        });
        setGenerated(res.data);
        setEditedSubject(res.data.subject);
        setEditedBody(res.data.body);
      } catch (err) {
        setError(err.response?.data?.detail || 'Erreur lors de la génération');
      } finally {
        setLoading(false);
      }
    },
    [channel, customInstructions, initialLeadId, selectedLead, tone]
  );

  useEffect(() => {
    if (!initialLeadId || autoGeneratedRef.current) return;
    autoGeneratedRef.current = true;
  }, [handleGenerate, initialLeadId]);

  const handleRewriteWithInstructions = () => {
    if (!customInstructions.trim()) {
      setError('Ajoutez au moins un point à intégrer avant de réécrire.');
      return;
    }
    handleGenerate(customInstructions);
  };

  const handleSave = async () => {
    if (!selectedLead && !initialLeadId) return;
    setSaving(true);
    try {
      const payload = {
        channel,
        subject: editedSubject,
        body: editedBody,
        body_html: bodyToHtml(editedBody),
      };

      if (existingMessage?.id) {
        await messagesApi.update(existingMessage.id, payload);
      } else {
        await messagesApi.create({
          ...payload,
          lead_id: generated?.lead_id || Number(selectedLead || initialLeadId),
        });
      }
      onSaved();
      onClose();
    } catch (err) {
      setError(err.response?.data?.detail || 'Erreur lors de la sauvegarde');
    } finally {
      setSaving(false);
    }
  };

  const handleCopy = async () => {
    await copyRichEmail(editedBody);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 bg-black/40 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.95 }}
        className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto"
      >
        <div className="flex items-center justify-between p-6 border-b border-gray-100">
          <h2 className="text-lg font-bold text-primary-900 flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-accent-500" /> Générer un message IA
          </h2>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-gray-100 transition-colors"
          >
            <X className="w-4 h-4 text-primary-500" />
          </button>
        </div>

        <div className="p-6 space-y-5">
          {isTargeted ? (
            <div className="rounded-xl border border-accent-100 bg-accent-50/70 px-4 py-3">
              <p className="text-xs font-semibold uppercase tracking-wide text-accent-700">
                Travail ciblé
              </p>
              <p className="mt-1 text-sm font-semibold text-primary-900">
                {initialLeadName || `Lead #${initialLeadId}`}
              </p>
              <p className="mt-1 text-xs text-primary-500">
                Génération puis correction manuelle avant copie. Aucun envoi automatique.
              </p>
            </div>
          ) : (
            <div>
              <label className="block text-sm font-medium text-primary-700 mb-1.5">
                Prospect cible
              </label>
              <select
                value={selectedLead}
                onChange={(e) => setSelectedLead(e.target.value)}
                className="w-full px-3 py-2.5 rounded-xl border border-primary-200 text-sm text-primary-900 bg-white focus:outline-none focus:ring-2 focus:ring-accent-400"
              >
                <option value="">Sélectionnez un prospect...</option>
                {leads.map((l) => (
                  <option key={l.id} value={l.id}>
                    {l.name}
                    {l.city ? ` — ${l.city}` : ''} (score: {l.score})
                  </option>
                ))}
              </select>
            </div>
          )}

          {/* Canal + Ton */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-primary-700 mb-1.5">Canal</label>
              <div className="flex gap-2">
                {[
                  { v: 'email', label: 'Email' },
                  { v: 'linkedin', label: 'LinkedIn' },
                ].map(({ v, label }) => (
                  <button
                    key={v}
                    type="button"
                    onClick={() => setChannel(v)}
                    className={`flex-1 flex items-center justify-center gap-1.5 py-2 rounded-xl border text-sm font-medium transition-colors
                      ${channel === v ? 'bg-accent-500 text-white border-accent-500' : 'bg-gray-50 text-primary-600 border-gray-200 hover:bg-gray-100'}`}
                  >
                    {v === 'email' ? (
                      <Mail className="w-4 h-4" />
                    ) : (
                      <Linkedin className="w-4 h-4" />
                    )}
                    {label}
                  </button>
                ))}
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium text-primary-700 mb-1.5">Ton</label>
              <select
                value={tone}
                onChange={(e) => setTone(e.target.value)}
                className="w-full px-3 py-2 rounded-xl border border-primary-200 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-accent-400"
              >
                <option value="friendly">Amical</option>
                <option value="professional">Professionnel</option>
                <option value="direct">Direct</option>
              </select>
            </div>
          </div>

          {error && (
            <div className="flex items-center gap-2 text-red-600 text-sm p-3 bg-red-50 rounded-xl border border-red-200">
              <AlertCircle className="w-4 h-4 flex-shrink-0" />
              {error}
            </div>
          )}

          <div className="rounded-xl border border-accent-200 bg-accent-50/60 p-4 space-y-3">
            <div>
              <p className="text-sm font-semibold text-primary-900">
                Points à intégrer dans la réécriture
              </p>
              <p className="text-xs text-primary-500 mt-1">
                Exemple : proposer une landing page, signaler une visibilité web faible, ajouter une
                carte de géolocalisation, intégrer les avis clients.
              </p>
            </div>
            <textarea
              value={customInstructions}
              onChange={(e) => setCustomInstructions(e.target.value)}
              rows={4}
              maxLength={500}
              placeholder="Écris ici tes points précis à intégrer dans le mail..."
              className="w-full px-3 py-2.5 rounded-xl border border-accent-200 text-sm text-primary-900 resize-y focus:outline-none focus:ring-2 focus:ring-accent-400"
            />
            <div className="flex items-center justify-between gap-3">
              <span className="text-xs text-primary-400">
                {customInstructions.length}/500 caractères
              </span>
              <button
                onClick={handleRewriteWithInstructions}
                disabled={loading || !customInstructions.trim()}
                className="px-3 py-2 rounded-lg bg-accent-500 text-white text-xs font-semibold hover:bg-accent-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-1.5"
              >
                {loading ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Sparkles className="w-4 h-4" />
                )}
                Réécrire avec ces informations
              </button>
            </div>
          </div>

          {!existingMessage && (
            <button
              onClick={() => handleGenerate()}
              disabled={(!selectedLead && !initialLeadId) || loading}
              className="w-full py-2.5 rounded-xl border border-primary-200 text-primary-700 font-semibold text-sm hover:bg-primary-50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              <Sparkles className="w-4 h-4" />
              Générer sans consigne
            </button>
          )}

          {/* Résultat généré */}
          {(generated || existingMessage) && (
            <motion.div {...fadeUp} className="space-y-3 pt-2 border-t border-gray-100">
              <div>
                <label className="block text-xs font-medium text-primary-500 mb-1">Objet</label>
                <input
                  value={editedSubject}
                  onChange={(e) => setEditedSubject(e.target.value)}
                  className="w-full px-3 py-2 rounded-lg bg-gray-50 border border-gray-200 text-sm font-semibold text-primary-900 focus:outline-none focus:ring-2 focus:ring-accent-400"
                />
              </div>
              <div>
                <label className="block text-xs font-medium text-primary-500 mb-1">
                  Corps du message (modifiable)
                </label>
                <textarea
                  value={editedBody}
                  onChange={(e) => setEditedBody(e.target.value)}
                  rows={10}
                  className="w-full px-3 py-2.5 rounded-xl border border-primary-200 text-sm text-primary-900 resize-y focus:outline-none focus:ring-2 focus:ring-accent-400"
                />
              </div>
              <div className="flex gap-2">
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1.5 px-3 py-2 rounded-lg border border-gray-200 text-sm text-primary-600 hover:bg-gray-50 transition-colors"
                >
                  {copied ? (
                    <CheckCircle className="w-4 h-4 text-green-600" />
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                  {copied ? 'Copié !' : 'Copier'}
                </button>
                <button
                  onClick={handleSave}
                  disabled={saving}
                  className="flex-1 flex items-center justify-center gap-1.5 py-2 rounded-lg bg-accent-500 text-white text-sm font-medium hover:bg-accent-600 transition-colors disabled:opacity-50"
                >
                  {saving ? (
                    <Loader2 className="w-4 h-4 animate-spin" />
                  ) : (
                    <Plus className="w-4 h-4" />
                  )}
                  {existingMessage?.id
                    ? 'Mettre à jour le brouillon'
                    : 'Sauvegarder comme brouillon'}
                </button>
              </div>
            </motion.div>
          )}
        </div>
      </motion.div>
    </div>
  );
}

// ─── Page principale ──────────────────────────────────────────────────────────
export default function Messages() {
  const [messages, setMessages] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [generationTarget, setGenerationTarget] = useState(null);
  const { toast, showToast } = useToast();
  const [copied, setCopied] = useState(null);
  const [campaigns, setCampaigns] = useState([]);
  const [selectedCampaign, setSelectedCampaign] = useState('');
  const [leadNames, setLeadNames] = useState({});
  const [expandedId, setExpandedId] = useState(null);
  const [currentIndex, setCurrentIndex] = useState(0);

  const fetchMessages = useCallback(async (campaignId = '') => {
    setLoading(true);
    setError(null);
    try {
      const params = { per_page: 100, page: 1 };
      if (campaignId) params.campaign_id = campaignId;
      const res = await messagesApi.list(params);
      const msgs = res.data.messages || [];
      setMessages(msgs);
      setCurrentIndex(0);
      // Charger les noms des leads en un seul appel
      const uniqueLeadIds = [...new Set(msgs.map((m) => m.lead_id).filter(Boolean))];
      if (uniqueLeadIds.length > 0) {
        try {
          const r = await leadsApi.names(uniqueLeadIds.join(','));
          setLeadNames(r.data);
        } catch {
          /* fallback : pas de noms */
        }
      }
    } catch {
      setError('Impossible de charger les messages. Vérifiez que le backend tourne.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    campaignsApi
      .list({ per_page: 50 })
      .then((r) => setCampaigns(r.data.campaigns || []))
      .catch(() => {});
  }, []);

  useEffect(() => {
    fetchMessages(selectedCampaign);
  }, [fetchMessages, selectedCampaign]);

  const handleCopy = async (id, body) => {
    await copyRichEmail(body);
    setCopied(id);
    setTimeout(() => setCopied(null), 2000);
  };

  return (
    <div className="space-y-8">
      <AnimatePresence>
        {generationTarget && (
          <GenerateModal
            initialLeadId={generationTarget.lead_id}
            initialLeadName={
              leadNames[generationTarget.lead_id] || `Lead #${generationTarget.lead_id}`
            }
            existingMessage={generationTarget}
            onClose={() => {
              setGenerationTarget(null);
            }}
            onSaved={() => {
              fetchMessages(selectedCampaign);
              showToast('Brouillon mis à jour');
            }}
          />
        )}
      </AnimatePresence>

      {/* Toast */}
      <AnimatePresence>
        {toast && (
          <motion.div
            initial={{ opacity: 0, y: -16 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -16 }}
            className="fixed top-6 right-6 z-50 flex items-center gap-2 bg-green-600 text-white text-sm font-medium px-4 py-3 rounded-xl shadow-lg"
          >
            <CheckCircle className="w-4 h-4" />
            {toast.msg || toast.message || toast}
          </motion.div>
        )}
      </AnimatePresence>

      {/* En-tête */}
      <motion.div {...fadeUp} className="flex items-end justify-between">
        <div>
          <h1 className="text-3xl font-display font-bold text-primary-900">Messages</h1>
          <p className="mt-1 text-primary-500">
            Travail manuel un par un : générer, corriger, copier.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={() => fetchMessages(selectedCampaign)}
            className="p-2 rounded-xl border border-primary-200 hover:bg-primary-50 transition-colors"
            title="Rafraîchir"
          >
            <RefreshCw className="w-4 h-4 text-primary-500" />
          </button>
        </div>
      </motion.div>

      {/* Filtre par campagne */}
      <motion.div {...fadeUp} className="flex items-center gap-3">
        <select
          value={selectedCampaign}
          onChange={(e) => setSelectedCampaign(e.target.value)}
          className="px-3 py-2 rounded-xl border border-primary-200 text-sm text-primary-800 bg-white focus:outline-none focus:ring-2 focus:ring-accent-400 min-w-[220px]"
        >
          <option value="">Toutes les campagnes</option>
          {campaigns.map((c) => (
            <option key={c.id} value={c.id}>
              {c.name}
            </option>
          ))}
        </select>
        {selectedCampaign && (
          <button
            onClick={() => setSelectedCampaign('')}
            className="text-xs text-primary-400 hover:text-primary-600 underline"
          >
            Effacer le filtre
          </button>
        )}
        <span className="text-sm text-primary-400">
          {messages.length} message{messages.length > 1 ? 's' : ''}
        </span>
      </motion.div>

      {/* Erreur */}
      {error && (
        <motion.div
          {...fadeUp}
          className="p-4 rounded-2xl border border-red-200 bg-red-50 flex items-center gap-3 text-red-600"
        >
          <AlertCircle className="w-5 h-5 flex-shrink-0" />
          <p className="text-sm">{error}</p>
        </motion.div>
      )}

      {/* Contenu */}
      {loading ? (
        <div className="flex items-center justify-center py-24">
          <Loader2 className="w-8 h-8 text-accent-500 animate-spin" />
        </div>
      ) : messages.length === 0 ? (
        <motion.div
          {...fadeUp}
          className="bg-white rounded-2xl shadow-sm border border-gray-100 p-16 flex flex-col items-center justify-center text-center"
        >
          <div className="p-4 rounded-2xl bg-accent-50 mb-4">
            <MessageSquare className="w-10 h-10 text-accent-400" />
          </div>
          <p className="font-semibold text-primary-700 text-lg mb-1">Liste nettoyée</p>
          <p className="text-primary-400 text-sm">
            Ajoutez un lead à une campagne pour travailler le message suivant.
          </p>
        </motion.div>
      ) : (
        <div className="space-y-4">
          {(() => {
            const msg = messages[currentIndex] || messages[0];
            const status = STATUS_STYLE[msg.status] || STATUS_STYLE.draft;
            const sentiment = SENTIMENT_STYLE[msg.sentiment] || SENTIMENT_STYLE.unknown;
            const date = msg.sent_at || msg.created_at;
            const dateStr = date
              ? new Date(date).toLocaleDateString('fr-FR', {
                  day: '2-digit',
                  month: 'short',
                  hour: '2-digit',
                  minute: '2-digit',
                })
              : '—';
            return (
              <motion.div
                key={msg.id}
                {...fadeUp}
                transition={{ duration: 0.3 }}
                className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 hover:shadow-md transition-shadow"
              >
                <div className="flex items-start justify-between mb-3">
                  <div className="flex items-start gap-3">
                    <div className="p-2 rounded-xl bg-accent-50 text-accent-500 mt-0.5">
                      {msg.channel === 'email' ? (
                        <Mail className="w-4 h-4" />
                      ) : (
                        <Linkedin className="w-4 h-4" />
                      )}
                    </div>
                    <div>
                      <p className="font-semibold text-primary-900 text-sm">
                        {leadNames[msg.lead_id] || `Lead #${msg.lead_id}`}
                      </p>
                      <div className="flex items-center gap-2 mt-1 flex-wrap">
                        <span
                          className={`px-2 py-0.5 rounded-full text-xs font-semibold ${status.cls}`}
                        >
                          {status.label}
                        </span>
                        {sentiment.label && (
                          <span
                            className={`px-2 py-0.5 rounded-full text-xs font-semibold ${sentiment.cls}`}
                          >
                            {sentiment.label}
                          </span>
                        )}
                        {msg.subject && (
                          <span className="text-xs text-primary-500 truncate max-w-xs">
                            — {msg.subject}
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                  <span className="text-xs text-primary-400 flex-shrink-0 ml-4">{dateStr}</span>
                </div>

                <div
                  className="text-sm text-primary-600 bg-gray-50 rounded-xl p-4 cursor-pointer"
                  onClick={() => setExpandedId(expandedId === msg.id ? null : msg.id)}
                >
                  <p
                    className={`whitespace-pre-wrap ${expandedId === msg.id ? '' : 'line-clamp-6'}`}
                  >
                    {msg.body}
                  </p>
                  <p className="text-xs text-primary-400 mt-1 text-right">
                    {expandedId === msg.id ? '▲ Réduire' : '▼ Voir le message complet'}
                  </p>
                </div>

                <div className="mt-4 space-y-2">
                  <div className="flex items-center justify-between gap-3">
                    <div className="flex items-center gap-2 text-sm text-primary-500">
                      <button
                        onClick={() => {
                          setCurrentIndex((idx) => Math.max(0, idx - 1));
                          setExpandedId(null);
                        }}
                        disabled={currentIndex === 0}
                        className="px-3 py-1.5 rounded-lg border border-gray-200 hover:bg-gray-50 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
                      >
                        Précédent
                      </button>
                      <span className="text-xs text-primary-400">
                        {currentIndex + 1} / {messages.length}
                      </span>
                      <button
                        onClick={() => {
                          setCurrentIndex((idx) => Math.min(messages.length - 1, idx + 1));
                          setExpandedId(null);
                        }}
                        disabled={currentIndex >= messages.length - 1}
                        className="px-3 py-1.5 rounded-lg border border-gray-200 hover:bg-gray-50 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
                      >
                        Suivant
                      </button>
                    </div>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => {
                          setGenerationTarget(msg);
                        }}
                        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-accent-200 bg-accent-50 text-accent-700 text-xs font-semibold hover:bg-accent-100 transition-colors"
                        title="Ajouter des points puis réécrire"
                      >
                        <Plus className="w-4 h-4" />
                        Apporter des modifications
                      </button>
                      <button
                        onClick={() => handleCopy(msg.id, msg.body)}
                        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-accent-500 text-white text-xs font-medium hover:bg-accent-600 transition-colors"
                        title="Copier"
                      >
                        {copied === msg.id ? (
                          <CheckCircle className="w-4 h-4" />
                        ) : (
                          <Copy className="w-4 h-4" />
                        )}
                        {copied === msg.id ? 'Copié' : 'Copier pour envoi manuel'}
                      </button>
                    </div>
                  </div>
                </div>
              </motion.div>
            );
          })()}
        </div>
      )}
    </div>
  );
}
